# Numpy(Numerical python) : 
**Is a library consisting of multidimensional array objects and a collection of routines(functions) for processing those arrays.**<br>**Using NumPy, mathematical and logical operations on arrays can be performed.**
## Operation using numpy 
* Mathematical and logical operations on arrays.<br>
* Fourier transforms and routines for shape manipulation.<br>
* Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.<br>

## Numpy Array object 

NumPy has a multidimensional array object called ndarray. It consists of two parts
as follows:<br>
* The actual data
* Some metadata describing the data<br>
The majority of array operations leave the raw data untouched. The only aspect that
changes is the metadata.

In [1]:
#Convention to import numpy
import numpy as np

## Numpy - ndarray(n dimentional array) object


In [51]:
# Creating array of dimenion 3 for example
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
#To spicify the minimum dimenion of the array we use the default parameter ndim
B=np.array([1,2,3],ndmin=2)
print(B)
print(B.ndim)
#note the difference
B=np.array([1,2,3])
print(B)
print(B.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
2
[1 2 3]
1


## NumPy numerical types 

#### We use default argument (dtype) to determine the data type of elements of array 
#### There are many data types:
|Type | Description |
|:---|--------:|
|bool |This stores boolean (True or False) as a bit|
|inti |This is a platform integer (normally either int32 or int64)|
|int8 |This is an integer ranging from-128 to 127|
|int16 |This is an integer ranging from -32768 to 32767|
|int32 |This is an integer ranging from -2 ** 31 to 2 ** 31 -1|
|int64 |This is an integer ranging from -2 ** 63 to 2 ** 63 -1|
|uint8 |This is an unsigned integer ranging from 0 to 255|
|uint16 |This is an unsigned integer ranging from 0 to 65535|
|uint32 |This is an unsigned integer ranging from 0 to 2 ** 32 - 1|
|uint64 |This is an unsigned integer ranging from 0 to 2 ** 64 - 1|
|float16 |This is a half precision float with sign bit, 5 bits exponent, and 10 bits mantissa|
|float32 |This is a single precision float with sign bit, 8 bits exponent, and 23 bits mantissa|
|float64 or float |This is a double precision float with sign bit, 11 bits exponent, and52 bits mantissa|
|complex64|This is a complex number represented by two 32-bit floats (real and imaginary components)|
|complex128 or complex|This is a complex number represented by two 64-bit floats (real and imaginary components)|

**Each built-in data type has a character code that uniquely identifies it**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'd' − double

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

In [7]:
#For each data type, there exists a corresponding conversion function
np.float(5),np.float128(15),np.complex128(1),np.bool(2),np.int64(44.2)

(5.0, 15.0, (1+0j), True, 44)

In [9]:
#It is important to know that you are not allowed to convert a complex number into
#an integer type number. 
np.int64(1+2j) #error

In [24]:
#An example 
#Note to access these type use
#np.type or "type"
C=np.array([1,2,3],dtype="uint8")
print(C)
D=np.array([1+2j,3+3j,4+5j])
print(D)
print(D.dtype)
D=np.array([1+2j,3+3j,4+5j],dtype=np.complex64)
print(D)

[1 2 3]
[1.+2.j 3.+3.j 4.+5.j]
complex128
[1.+2.j 3.+3.j 4.+5.j]


## dtype constructors

In [24]:
np.dtype(np.int16) 

(dtype('int16'), dtype('int8'), dtype('int16'), dtype('int32'), dtype('int32'))

In [25]:
#We can give a data type constructor a two-character code. The first character
#signifies the type, and the second character is a number specifying the
#number of bytes in the data type
np.dtype('i1'),np.dtype('i2'),np.dtype('i4'),np.dtype('i')

(dtype('int8'), dtype('int16'), dtype('int32'), dtype('int32'))

In [26]:
np.dtype('f'),np.dtype('f8')

(dtype('float32'), dtype('float64'))

In [13]:
np.dtype('d')

dtype('float64')

## Creating a record data type
A record data type is a heterogeneous data type

In [40]:
#Like struct in C we create our structed data type 
# we use np.dtype function
student=np.dtype([('name',np.str,10),('class',np.int8),('mark',np.uint16)])
#when we enter the elements of the array we must enter every element of the array as a tuple of three elements 
students=np.array([("abdullah",2,19),('ahmed',1,20),('reham',2,17)],dtype=student)
print(students[0])
print(students)
print(students['name'])

('abdullah', 2, 19)
[('abdullah', 2, 19) ('ahmed', 1, 20) ('reham', 2, 17)]
['abdullah' 'ahmed' 'reham']



|/|name|class|mark|
|-|---|-----|----|
|0|abdullah|2|19|
|1|ahmed|1|20|
|2|reham|2|17|