# Numpy(Numerical python ) : 
**Is a library consisting of multidimensional array objects and a collection of routines(functions) for processing those arrays.**<br>**Using NumPy, mathematical and logical operations on arrays can be performed.**
## Operation using numpy 
-Mathematical and logical operations on arrays.<br>
-Fourier transforms and routines for shape manipulation.<br>
-Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.<br>

In [1]:
#Convention to import numpy
import numpy as np

## Numpy - ndarray(n dimentional array) object


In [51]:
# Creating array of dimenion 3 for example
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
#To spicify the minimum dimenion of the array we use the default parameter ndim
B=np.array([1,2,3],ndmin=2)
print(B)
print(B.ndim)
#note the difference
B=np.array([1,2,3])
print(B)
print(B.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
2
[1 2 3]
1


### Data types of element(dtype)

#### We use default argument(dtype) to determine the data type of elements of array 
#### There are many data types:
These types defined in numpy<br>
like bool_ ,int8 and uint8,int16 and uint16 ,and so on<br>
float16,float32,float64,float_(Shorthand for float64)<br>
complex64,complex128,complex_(Shorthand for complex128)<br>

In [24]:
#An example 
#Note to access these type use
#np.type or "type"
C=np.array([1,2,3],dtype="uint8")
print(C)
D=np.array([1+2j,3+3j,4+5j])
print(D)
print(D.dtype)
D=np.array([1+2j,3+3j,4+5j],dtype=np.complex64)
print(D)

[1 2 3]
[1.+2.j 3.+3.j 4.+5.j]
complex128
[1.+2.j 3.+3.j 4.+5.j]


# Creating our data type 

In [50]:
#Like struct in C we create our structed data type 
# we use np.dtype function
student=np.dtype([('name','S10'),('class',np.int8),('mark',np.uint16)])
#when we enter the elements of the array we must enter every element of the array as a tuple of three elements 
students=np.array([("abdullah",2,19),('ahmed',1,20),('reham',2,17)],dtype=student)
print(students)
print(students['name'])

[(b'abdullah', 2, 19) (b'ahmed', 1, 20) (b'reham', 2, 17)]
[b'abdullah' b'ahmed' b'reham']


**Each built-in data type has a character code that uniquely identifies it**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)