# empty array (unintialiezed array)

In [1]:
import numpy as np
A=np.empty((2,3),dtype='i1')
print(A)

[[0 0 0]
 [0 0 0]]


# zeros array

In [8]:
O=np.zeros(10)
print(O)
O=np.zeros((3,2))
print(O)
O=np.zeros((2,5),dtype=[('x','i1'),('y','i1')])
print(O)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]]


# ones array

In [9]:
B=np.ones((3,3),dtype="uint8")
print(B)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# eye array

In [5]:
I=np.eye(3,dtype='i1')
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# diagonal array

In [6]:
D=np.diag([1,2,3])
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# `arange`(start,end,step,dtype) function

In [25]:
C1=np.arange(0,10)
print(C1)
C2=np.arange(0,11)
print(C2)
C3=np.arange(10,0,-1)
print(C3)
C4=np.arange(1,11,2)
print(C4)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
[1 3 5 7 9]


# For linear space 
# `linspace`(start,stop,num=50,endpoint=True,retstep=False,dtype=None) function
To creat numbers between interval<br>
**endpoint**:True by default, hence the stop value is included in the sequence. If false, it is not included.<br>
**retstep**:If true, returns samples and step between the consecutive numbers.
**step** = $\frac{stop - start}{num-1}$

In [8]:
#step=(stop-start)/(num-1)
L1=np.linspace(0,10,num=6)
print(L1)
L2=np.linspace(-50,0,11)
print(L2)
L3=np.linspace(1,10,11,retstep=True)
step=L3[1]
array=L3[0]
print(step)
print(array)

[ 0.  2.  4.  6.  8. 10.]
[-50. -45. -40. -35. -30. -25. -20. -15. -10.  -5.   0.]
0.9
[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


# `logspace`(start,end,num,endpoint,base=10.0,dtype) function
**base**:base of $\log$<br>
it returns $x$ for example $\log_{10}x=20$ 

In [3]:
P=np.logspace(1,2,5,dtype='f2')
print(P)

[ 10.    17.78  31.62  56.22 100.  ]


In [6]:
P=np.linspace(1,5,3)
print(P)

[1. 3. 5.]


In [7]:
list(map(lambda x:10**x,P))

[10.0, 1000.0, 100000.0]

In [12]:
P=np.logspace(1,5,3,dtype="i4")
print(P)

[    10   1000 100000]
