In [11]:
import numpy as np
#creating array one dimension from 0 to 9
A=np.arange(10)
# As in python 
#by scile function slice(start index,end index,step)
s=slice(0,5)
A[s]
#or by slicing operator
A[0:5]

array([0, 1, 2, 3, 4])

In [12]:
A[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
A[1:3]=2
A

array([0, 2, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
A[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 2, 0])

In [10]:
A[:-1]#0 to index -2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
A[-1:3:-1]

array([9, 8, 7, 6, 5, 4])

In [19]:
B=np.arange(20)
B=B.reshape(5,4)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [10]:
#slicing rows
B[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
B[2:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
B[::-1] #reversing rows

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

## 2-D array slicing 

In [47]:
print(B[::-1][::-1])# equivalent to (B[::-1])[::-1]  #reversing rows 2 times
print("--------------------")
print(B[::-1,::-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
--------------------
[[19 18 17 16]
 [15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [18]:
#slicing columns
#you can use ellipsis(...) as translated for every row or colum according to position
B[...,1]
#as B[:,1]

array([ 1,  5,  9, 13, 17])

In [126]:
B[1,:] # as B[1]

array([4, 5, 6, 7])

In [37]:
B[:,1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

# Advanced Indexing
**Note**:Advanced indexing always returns a copy of the data

In [44]:
#normal indexing returns the same ref
y=B[0,:]
print(y)
y[0]=20
print(B)

[0 1 2 3]
[[20  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [51]:
#note the difference ,first is a ref and the second is a copy
B[1,2],B[[1],[2]]

(6, array([6]))

## 1.Integer Indexing
This mechanism helps in selecting any arbitrary item in an array based on its Ndimensional index<br>
Each integer array represents the number of indexes into that dimension.<br>
Array**\[**row list,col list**\]**

In [2]:
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [128]:
X[[0,2]]#retruns the row 0 and 2

array([[1, 2, 3],
       [7, 8, 9]])

In [24]:
print(X[:,[1,2]]) #returns column 1 and 2

[[2 3]
 [5 6]
 [8 9]]


In [70]:
X.T[[1,2]] #returns column 1 and 2

array([[2, 5, 8],
       [3, 6, 9]])

In [23]:
print(X[[0,2],[1,2]]) #returns array of X[0,1] and X[2,2]

[2 9]


In [75]:
#To copy all the array 
Y=X.copy()
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
Y=np.copy(X)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
print(X[[row for row in range(X.shape[0])]])
print(X[[0,1,2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 2.Booean Indexing
This type of advanced indexing is used when the resultant object is meant to be the result of Boolean operations

In [43]:
Y=X[True]
print(X)
print('\n')
print(Y)
print(Y[0])
Y.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


(1, 3, 3)

In [100]:
X[X>0]#iterates for every value in X

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
print(X[np.iscomplex(X)])

[]


In [3]:
print(X[X>3])

[4 5 6 7 8 9]
