# Generally most of methods of the array can be written as
**1.array.method()<br>
2.np.method(array)**

In [2]:
import numpy as np

In [3]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

### 1.`array.sum()`

In [39]:
A.sum()

45

### 2. `array.mean()`

In [40]:
A.mean()

5.0

### 3.`array.std()` and `array.var()`
std:The Standard Deviation is a measure of how spread out numbers are.<br>
var:variance

In [5]:
print(A.std())
print(A.var())

2.581988897471611
6.666666666666667


### 4.`array.copy()`

In [42]:
#To use the same array without affecting the original array
B=np.copy(A)
print(B)
id(A),id(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(11515208, 11504040)

### 5.`array.diagonal()`

In [43]:
A.diagonal()

array([1, 5, 9])

In [47]:
print(A.trace())
print(A.diagonal().sum())

15
15


### 6.`array.any()`
 Returns True if any of the elements of `array` evaluate to True.

In [51]:
A.any()

True

In [52]:
A.all()
#Returns True if all elements evaluate to True.

True

### 7.`array.sort()`
**row sort**

In [58]:
C=np.array([[9,8,4],[2,1,0]])
C.sort()
C

array([[4, 8, 9],
       [0, 1, 2]])

### 8.`array.flat`
 *returns 1-D iterator over the array*

In [5]:
print(A)
C=np.array(A.flat)
C

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# go through all elements in the array 
for i in A.flat:
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

### 9.`array.flatten()`
   *Returns a **copy** of the array in one dimension*

In [10]:
C=A.flatten()
print(C)

[1 2 3 4 5 6 7 8 9]


### 10.`array.ravel()`
*Returns a flatten array* (returns a view)

In [18]:
print(A)
print("\n")
C=A.ravel()
print(C)
C[0]=30
print('\n')
print(A)
#however id(A)!=id(C)
id(A),id(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[1 2 3 4 5 6 7 8 9]


[[30  2  3]
 [ 4  5  6]
 [ 7  8  9]]


(173018352, 21005000)

### 11.Unique Array

In [13]:
A=np.array([1,2,3,4,1,2])
A=set(A)
print(A)
A=np.array(A)
print(A)
#A is still a set

{1, 2, 3, 4}
{1, 2, 3, 4}


In [15]:
A=np.array([1,2,6,3,4,1,2])
A=np.unique(A) #<=============
A

array([1, 2, 3, 4, 6])