In [2]:
import numpy as np

In [3]:
A=np.matrix([[1,2],[3,4]])

In [6]:
A**2

matrix([[ 7, 10],
        [15, 22]])

In [5]:
A*A

matrix([[ 7, 10],
        [15, 22]])

In [22]:
A=np.array([[1,2],[3,4]])
print(A**2)
print(A*A)

[[ 1  4]
 [ 9 16]]
[[ 1  4]
 [ 9 16]]


In [25]:
np.reshape(A,4)
A.reshape(4)

array([1, 2, 3, 4])

In [26]:
A

array([[1, 2],
       [3, 4]])