**If the shape of two arrays is same ,then the arthimatic operation done for each element of the arry.**

In [1]:
import numpy as np
A=np.arange(9)
B=np.arange(9)
print(A,B)
print(A+B)

[0 1 2 3 4 5 6 7 8] [0 1 2 3 4 5 6 7 8]
[ 0  2  4  6  8 10 12 14 16]


**What is the two arrays are different in shape,The Broadcasting come.**
# broadcasting
 ***The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations.***<br>
 ***The smaller array is broadcast to the size of the larger array so that they have compatible shapes.***

In [2]:
#If the dimensions of two arrays are dissimilar, element-to-element operations are not possible.
A=np.arange(1,10)
A=A.reshape(3,3)
B=np.arange(1,4)
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [4]:
print(A+B)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


What is doning,B is broadcasted to 
$\left[ 1~2~3\\
~1~2~3\\
~1~2~3\right]$