In [1]:
import numpy as np

In [10]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [7]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [8]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [9]:
np.power(arr,2)
#arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
np.log2(arr[1:])

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [23]:
#ln() natural log
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [24]:
np.log10(arr[1:])

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

## Binary Functions

In [40]:
A=np.array([1,4,6,9,3,7])
B=np.array([2,6,9,2,5,4])
C=np.array([3,6,8,0,12,4])

In [13]:
np.add(A,B)
#A+B

array([ 3, 10, 15, 11,  8, 11])

In [15]:
np.subtract(A,B)
#A-B

array([-1, -2, -3,  7, -2,  3])

In [31]:
np.mod(A,B)
#A%B

array([1, 4, 6, 1, 3, 3])

In [14]:
np.maximum(A,B)

array([2, 6, 9, 9, 5, 7])

In [42]:
np.in1d(A,B)
# Test whether each element of a 1-D array is also present in a second array.

array([False,  True,  True,  True, False, False])